- name: Converge
  hosts: all
  become: true

  pre_tasks:
  - name: Update apt cache.
    apt: update_cache=yes cache_valid_time=600
    when: ansible_os_family == 'Debian'

  roles:
  - role: cvmfs_contrib.cvmfs_client
    vars:
      cvmfs_cache_size: "1000"  # small cache size for CI
      cvmfs_http_proxy: "http://cvmfs-cache.arbutus.cloud.computecanada.ca:3128;DIRECT"
