- name: Verify
  hosts: all
  become: true

  tasks:
  - name: CVMFS check setup
    command: cvmfs_config chksetup

  - name: CVMFS probe
    command: cvmfs_config probe

  - name: Search for a module on Compute Canda repo
    shell: >
      source /cvmfs/soft.computecanada.ca/config/profile/bash.sh &&
      module spider quantumespresso/6.8